import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { OperationBus } from "../src/operation-bus.js";
import { TransactionalExecutor } from "../src/transactional-executor.js";
import { InstallTransaction } from "../src/install-transaction.js";
const actor = { id: "user-a", channel: "test", sessionId: "session-a" };
function fixture() { const root = mkdtempSync(join(tmpdir(), "operation-bus-")); const executor = new TransactionalExecutor({ roots: [root] }); const bus = new OperationBus({ dbPath: join(root, "bus.sqlite"), executor }); return { root, bus, executor, close() { bus.close(); rmSync(root, { recursive: true, force: true }); } }; }
function plan(input = {}) { return { actor, summary: "test", purpose: "test", actions: [{ type: "filesystem.write", target: input.target, content: input.content || "frozen" }], ...input }; }
test("freezes plan, consumes confirmation once, and audits", async () => { const f = fixture(); try { const target = join(f.root, "frozen.txt"), op = f.bus.createPlan(plan({ target })), hash = op.canonicalHash; op.actions[0].content = "attacker"; assert.equal(f.bus.authorize({ operationId: op.operationId, canonicalHash: hash, actor }).ok, true); assert.equal((await f.bus.execute(op.operationId)).ok, true); assert.equal(readFileSync(target, "utf8"), "frozen"); assert.equal(f.bus.authorize({ operationId: op.operationId, canonicalHash: hash, actor }).code, "ALREADY_CONSUMED"); assert.ok(f.bus.auditFor(op.operationId).some((entry) => entry.event === "execution.succeeded")); } finally { f.close(); } });
test("rejects scope/hash mismatches and scoped authorization remains narrow", () => { const f = fixture(); try { const op = f.bus.createPlan(plan({ target: join(f.root, "a") })); assert.equal(f.bus.authorize({ operationId: op.operationId, canonicalHash: "sha256:bad", actor }).code, "HASH_MISMATCH"); assert.equal(f.bus.authorize({ operationId: op.operationId, canonicalHash: op.canonicalHash, actor: { ...actor, channel: "other" } }).code, "ACTOR_SCOPE_MISMATCH"); const auth = f.bus.createAuthorization({ type: "SCOPED_TIME_WINDOW", actor, scope: { operationClasses: ["filesystem.write"], pathRoots: [f.root] }, expiresAt: Date.now() + 600000 }); assert.equal(f.bus.authorize({ operationId: op.operationId, canonicalHash: op.canonicalHash, actor, authorizationId: auth.authorizationId }).ok, true); const outside = f.bus.createPlan(plan({ target: "/tmp/outside-not-authorized" })); assert.equal(f.bus.authorize({ operationId: outside.operationId, canonicalHash: outside.canonicalHash, actor, authorizationId: auth.authorizationId }).code, "AUTHORIZATION_SCOPE_DENIED"); const restarted = new OperationBus({ dbPath: join(f.root, "bus.sqlite"), executor: f.executor, bootId: "new-boot" }); const other = f.bus.createPlan(plan({ target: join(f.root, "b") })); assert.equal(restarted.authorize({ operationId: other.operationId, canonicalHash: other.canonicalHash, actor, authorizationId: auth.authorizationId }).code, "AUTHORIZATION_SCOPE_DENIED"); restarted.close(); } finally { f.close(); } });
test("financial actions require explicit per-operation confirmation", () => { const f = fixture(); try { const op = f.bus.createPlan({ actor, summary: "transfer", purpose: "mock", actions: [{ type: "transaction.transfer", recipient: "mock", amount: "20", currency: "USD" }] }); assert.equal(op.confirmationMode, "FINANCIAL_STEP_UP"); assert.equal(f.bus.authorize({ operationId: op.operationId, canonicalHash: op.canonicalHash, actor: { ...actor, confirmationText: "确认" } }).code, "FINANCIAL_CONFIRMATION_REQUIRED"); assert.equal(f.bus.authorize({ operationId: op.operationId, canonicalHash: op.canonicalHash, actor: { ...actor, confirmationText: `确认转账 ${op.operationId}` } }).ok, true); } finally { f.close(); } });
test("isolated installation detects plan mismatch and commits MCP skill", async () => { const root = mkdtempSync(join(tmpdir(), "install-")); try { const source = join(root, "source"); mkdirSync(source); writeFileSync(join(source, "SKILL.md"), "# test"); writeFileSync(join(source, "openclaw-skill.json"), JSON.stringify({ id: "mcp-skill", mcpServers: [{ name: "test", transport: "streamable-http", url: "https://example.invalid/mcp", auth: { type: "bearer-env", env: "TEST_TOKEN" } }] })); const config = join(root, "config.json"); writeFileSync(config, "{}\n"); const tx = new InstallTransaction({ stagingRoot: join(root, "staging"), skillsRoot: join(root, "skills"), configPath: config }); const prepared = tx.prepare({ operationId: "op_stage", sourcePath: source }); assert.equal(readFileSync(config, "utf8"), "{}\n"); writeFileSync(join(prepared.stage, "payload", "changed"), "x"); await assert.rejects(tx.commit({ operationId: "op_stage", expectedHash: prepared.hash }), /PLAN_MISMATCH/); tx.cleanup("op_stage"); const clean = tx.prepare({ operationId: "op_commit", sourcePath: source }); assert.equal((await tx.commit({ operationId: "op_commit", expectedHash: clean.hash })).ok, true); assert.match(readFileSync(config, "utf8"), /TEST_TOKEN/); } finally { rmSync(root, { recursive: true, force: true }); } });
test("dynamic shell, secrets and irreversible deletion are denied", () => { const f = fixture(); try { assert.throws(() => f.bus.createPlan({ actor, actions: [{ type: "process.spawn", argv: ["bash", "-c", "x"] }] }), /dynamic shell/); assert.equal(f.bus.createPlan({ actor, actions: [{ type: "filesystem.delete", target: join(f.root, "x"), irreversible: true }] }).status, "DENIED"); assert.throws(() => f.bus.createPlan({ actor, actions: [{ type: "filesystem.write", target: join(f.root, "x"), content: "token=secret" }] }), /secret material/); } finally { f.close(); } });
