export const ADMIN_CAPABILITIES = new Set([
  "CONFIG_MUTATION", "SECURITY_POLICY_MUTATION", "SECURITY_COMPONENT_MUTATION", "REGISTRY_MUTATION", "APPROVALS_MUTATION", "SKILL_INSTALL", "SKILL_UPGRADE", "SKILL_UNINSTALL", "BOOTSTRAP_MUTATION", "INTEGRITY_REFRESH", "GATEWAY_REPAIR"
]);

export function adminPlaneRequired(capability) {
  return ADMIN_CAPABILITIES.has(capability?.kind) ? "ADMIN_PLANE_REQUIRED: 该操作只能通过服务器本地 openclaw-admin 执行" : "";
}
